from sqlalchemy import Column, Float, Integer, JSON, String

from persistence.database_engine_factory import database_engine


class NutritionEntity(database_engine.Base):
    """
    SQLAlchemy entity representing a nutrition record in the database.
    """

    __tablename__ = "nutrition"

    id = Column(Integer, primary_key=True)
    code = Column(String, nullable=True)
    name = Column(String, nullable=False)
    url = Column(String, nullable=True)
    brands = Column(JSON, nullable=True)
    synonyms = Column(JSON, nullable=True)
    categories = Column(JSON, nullable=True)
    quantity = Column(String, nullable=True)
    energy_100g_kj = Column(Float, nullable=False)
    fat_100g = Column(Float, nullable=False)
    saturated_fat_100g = Column(Float, nullable=True)
    butyric_acid_100g = Column(Float, nullable=True)
    caproic_acid_100g = Column(Float, nullable=True)
    caprylic_acid_100g = Column(Float, nullable=True)
    capric_acid_100g = Column(Float, nullable=True)
    lauric_acid_100g = Column(Float, nullable=True)
    myristic_acid_100g = Column(Float, nullable=True)
    palmitic_acid_100g = Column(Float, nullable=True)
    stearic_acid_100g = Column(Float, nullable=True)
    arachidic_acid_100g = Column(Float, nullable=True)
    behenic_acid_100g = Column(Float, nullable=True)
    lignoceric_acid_100g = Column(Float, nullable=True)
    cerotic_acid_100g = Column(Float, nullable=True)
    montanic_acid_100g = Column(Float, nullable=True)
    melissic_acid_100g = Column(Float, nullable=True)
    monounsaturated_fat_100g = Column(Float, nullable=True)
    polyunsaturated_fat_100g = Column(Float, nullable=True)
    alpha_linolenic_acid_100g = Column(Float, nullable=True)
    eicosapentaenoic_acid_100g = Column(Float, nullable=True)
    docosahexaenoic_acid_100g = Column(Float, nullable=True)
    linoleic_acid_100g = Column(Float, nullable=True)
    arachidonic_acid_100g = Column(Float, nullable=True)
    gamma_linolenic_acid_100g = Column(Float, nullable=True)
    dihomo_gamma_linolenic_acid_100g = Column(Float, nullable=True)
    oleic_acid_100g = Column(Float, nullable=True)
    elaidic_acid_100g = Column(Float, nullable=True)
    gondoic_acid_100g = Column(Float, nullable=True)
    mead_acid_100g = Column(Float, nullable=True)
    erucic_acid_100g = Column(Float, nullable=True)
    nervonic_acid_100g = Column(Float, nullable=True)
    trans_fat_100g = Column(Float, nullable=True)
    cholesterol_100g = Column(Float, nullable=True)
    carbohydrates_100g = Column(Float, nullable=False)
    sugars_100g = Column(Float, nullable=False)
    sucrose_100g = Column(Float, nullable=True)
    glucose_100g = Column(Float, nullable=True)
    fructose_100g = Column(Float, nullable=True)
    galactose_100g = Column(Float, nullable=True)
    lactose_100g = Column(Float, nullable=True)
    maltose_100g = Column(Float, nullable=True)
    maltodextrins_100g = Column(Float, nullable=True)
    starch_100g = Column(Float, nullable=True)
    fiber_100g = Column(Float, nullable=True)
    proteins_100g = Column(Float, nullable=False)
    salt_100g = Column(Float, nullable=False)
    alcohol_100g = Column(Float, nullable=True)
    vitamin_a_100g = Column(Float, nullable=True)
    beta_carotene_100g = Column(Float, nullable=True)
    vitamin_b1_100g = Column(Float, nullable=True)
    vitamin_b2_100g = Column(Float, nullable=True)
    vitamin_b3_100g = Column(Float, nullable=True)
    vitamin_b6_100g = Column(Float, nullable=True)
    vitamin_b9_100g = Column(Float, nullable=True)
    vitamin_b12_100g = Column(Float, nullable=True)
    pantothenic_acid_100g = Column(Float, nullable=True)
    vitamin_c_100g = Column(Float, nullable=True)
    vitamin_d_100g = Column(Float, nullable=True)
    vitamin_e_100g = Column(Float, nullable=True)
    vitamin_k_100g = Column(Float, nullable=True)
    potassium_100g = Column(Float, nullable=True)
    sodium_100g = Column(Float, nullable=True)
    chloride_100g = Column(Float, nullable=True)
    calcium_100g = Column(Float, nullable=True)
    magnesium_100g = Column(Float, nullable=True)
    phosphorus_100g = Column(Float, nullable=True)
    iron_100g = Column(Float, nullable=True)
    iodine_100g = Column(Float, nullable=True)
    zinc_100g = Column(Float, nullable=True)
    selenium_100g = Column(Float, nullable=True)
    folates_100g = Column(Float, nullable=True)
    biotin_100g = Column(Float, nullable=True)
    silica_100g = Column(Float, nullable=True)
    bicarbonate_100g = Column(Float, nullable=True)
    copper_100g = Column(Float, nullable=True)
    manganese_100g = Column(Float, nullable=True)
    fluoride_100g = Column(Float, nullable=True)
    chromium_100g = Column(Float, nullable=True)
    molybdenum_100g = Column(Float, nullable=True)
